### ISSUE TITLE
建议 `certConfig` 支持远程地址

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc-deploy#131]
当前 `certConfig` 中的 `certificate` 和 `privateKey` 只支持 pem 内容和本地文件路径, 对于需要经常更新 HTTPS 证书的用户而言用起来不是很方便 (每次证书更新都需要手动将证书下载至本地再进行 `s deploy domain`).

建议这两个属性可以支持以下协议:

+ [ ] `http://` 或 `https://` , 用户可以基于 DNS 或 PrivateZone 的内网解析保护密钥.
+ [ ] `oss://`  对象存储服务的文件地址, 用户可以基于对象存储服务的访问控制能力保护密钥.
+ [ ] `cas://` 假设是 SSL 证书管理 (云盾 SSL 证书) 的地址, 用户可以基于 RAM 的访问控制能力保护密钥. 

Ref:
+ 聆听建议: https://connect.console.aliyun.com/connect/detail/369545
+ https://github.com/Serverless-Devs/Serverless-Devs/discussions/400

**Comment by wss-git** [comment]
此功能已经发布，具体可以查看 https://github.com/devsapp/fc/issues/643
